---
- name: "Install an SQL database server"
  hosts: all
  gather_facts: yes
  vars:
    package: mariadb-server
  tasks:

  - name: Increase File System size for /opt
    aix_filesystem:
      filesystem: /opt
      size: +350M
      state: present
    when: ansible_distribution == 'AIX'

  - name: Increase File System size for /var
    aix_filesystem:
      filesystem: /var
      size: +250M
      state: present
    when: ansible_distribution == 'AIX'

  - name: Yum install "{{ package }}"
    yum:
      name: "{{ package }}"
      state: latest
    register: output
  - debug: var=output
