---
- name: "NIM check on AIX playbook"
  hosts: nimserver
  gather_facts: no

  collections:
  - ibm.power_aix
  tasks:

    - name: "AIX NIM"
      nim:
        action: 'check'
      register: result
    - debug: var=result
