---
dependencies: []
galaxy_info:
  author: Mariusz Czyz
  description: CentOS 7/8 and Fedora Apache Server Installation and Configuration Role
  license: BSD
  min_ansible_version: 2.4
  platforms:
    - name: EL
      versions:
        - 7
        - 8
    - name: Fedora
      versions:
        - 30
        - 31
  galaxy_tags:
    - centos
    - fedora
    - apache