---
- name: run aixpert security playbook
  hosts: aix
  gather_facts: False
## predefine your collection then use short name for moduels
  collections:
    - ibm.power_aix
  tasks:
    - name: "Query the settings"
      aixpert:
       mode: query
