---
- name: run lpar_facts playbook
  hosts: all
  gather_facts: false
  tasks:
    - name: Retrieve the LPAR related information
      ibm.power_aix.lpp_facts:
    - name: Print the fileset info 
      debug:
        var: ansible_facts.filesets
