---
# tasks file for install_httpd
#
  - name: Ensure that Apache is installed
    yum:
      name: httpd
      state: "{{ httpd_state }}"
    when: ansible_facts['os_family'] == "RedHat"

  - name: start Apache Service
    service:
      name: httpd
      enabled: yes
      state: started

  - name: Deploy configuration File
    template:
      src: httpd.j2
      dest: /etc/httpd/conf/httpd.conf
    notify:
      - Restart Apache
  - name: Create a directory if it does not exist
    file:
      path: /var/man/html/ansible
      state: directory
      mode: '0755'

  - name: copy site files
    file:
      path: /var/man/html/ansible/index.html
      state: touch


  - name: copy site files
    template:
      src: index.j2
      dest: /var/man/html/ansible/index.html
