---
- name: "This runs a command on target"
  hosts: all
  gather_facts: no
  tasks:
    - name: run command ls -l /usr
      command: "ls -l /usr"
      register: output

    - debug: var=output.stdout_lines
