---
- name : test conditional 
  hosts: all
  tasks:
  - name: run on  Debian flavored systems
    command: ls -l /
#    register: output
    when: ansible_facts['os_family'] == "Debian"
#  - debug:
#      var: output
