---
- name : test conditional 
  hosts: all
  tasks:
  - name: run on  Debian flavored systems
    command: ls -l /
#    register: output
    when: (ansible_facts['distribution'] == "RedHat" and ansible_facts['distribution_major_version'] == "7") or
          (ansible_facts['distribution'] == "Debian" and ansible_facts['distribution_major_version'] == "7")
#  - debug:
#      var: output
