---
- name: Deploy Ansible User
  hosts: all
  tasks:

    - name: Create Devops User
      user:
        name: faad
        append: true
        create_home: true
        comment: "Ansible Management Account"
        expires: -1
        password: "{{ 'Password1' | password_hash('sha512','A512') }}"
