---
- name: "This runs a fetch to bring back logfile for Ubuntu"
  gather_facts: no
  hosts: ubuntu-vsi
  tasks:
    - name: "Run fetch to get /var/log/syslog and put it in /tmp/clientlogs"
      fetch: 
        src: /var/log/syslog
        dest: /tmp/clientlogs
    - debug: 
        msg: "Getting /var/log/syslogp log file"

- name: "This runs a fetch to bring back logfile for REDHAT"
  gather_facts: no
  hosts: redhat-vsi
  tasks:
    - name: "run fetch to get /var/log/messages and put it in /tmp/clientlogs"
      fetch: 
        src: /var/log/messages
        dest: /tmp/clientlogs
    - debug: 
        msg: "Getting /var/log/messages log file"
