---
- name: "Install UNZIP package on  target using the package module"
  hosts: all
  gather_facts: no
  tasks:
    - name: "install unzip on aix, redhat and ubuntu"
      package:
        name: "{{ appname }}"
        state: :{{ appstate }}" 

    - debug: 
        msg: "Installed {{ appname }} on  {{ ansible_host }} "
