---
- name: "Install {{ appname }} package on target using the package module"
  hosts: all
  gather_facts: no
  tasks:
    - name: "install {{ appname }} on targets"
      package:
        name: "{{ appname }}"
        state: "{{ appstate }}" 

    - debug: 
        msg: "Installed {{ appname }} on  {{ ansible_host }} "
      when: appstate == "present"
    - debug: 
        msg: "Uninstalled {{ appname }} on  {{ ansible_host }} "
      when: appstate == "absent"
