---
## Play 1
- name: various var options
  hosts: all 
  gather_facts: no
  vars_prompt:
    - name: "my_password"
      prompt: "Enter password"
      default: "secret"
      private: yes
      confirm: yes
      encrypt: "md5_crypt"
      salt: 1234
      salt_size: 8
  tasks:
    - debug:
        msg: "password = {{ my_password }}"
    - name: create a user with that password
      user:
        name: test1
#        password: "{{ my_password | password_hash('sha512') }}"
#        password: "{{ my_password | password_hash('md5_crypt') }}"
        state: "{{ mystate }}"
        update_password: on_create
